services:
  web:
    build: ./backend
    container_name: autolead_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - .env
