# Generated by Django 5.2.4 on 2025-07-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('budget', models.CharField(blank=True, max_length=50, null=True)),
                ('average_bid', models.CharField(blank=True, max_length=50, null=True)),
                ('posted_time', models.CharField(max_length=50)),
                ('tags', models.JSONField(default=list)),
                ('url', models.URLField(unique=True)),
                ('client_country', models.CharField(blank=True, max_length=100, null=True)),
                ('client_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('client_total_jobs', models.CharField(blank=True, max_length=10, null=True)),
                ('client_total_spend', models.CharField(blank=True, max_length=50, null=True)),
                ('gpt_difficulty', models.IntegerField(blank=True, null=True)),
                ('gpt_intern', models.BooleanField(blank=True, null=True)),
                ('gpt_copilot', models.BooleanField(blank=True, null=True)),
                ('gpt_estimated_hours', models.FloatField(blank=True, null=True)),
                ('gpt_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_score', models.IntegerField(blank=True, null=True)),
                ('is_potential_lead', models.BooleanField(default=False)),
                ('is_sent_email', models.BooleanField(default=False)),
            ],
        ),
    ]
