# Generated by Django 5.2.4 on 2025-07-07 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upwork_crawler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='url',
            new_name='link',
        ),
    ]
