# Generated by Django 5.2.4 on 2025-07-07 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upwork_crawler', '0002_rename_url_job_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='link',
            new_name='url',
        ),
    ]
