# Generated by Django 5.2.4 on 2025-07-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upwork_crawler', '0003_rename_link_job_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='budget_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='budget_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
