# Generated by Django 5.2.4 on 2025-07-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upwork_crawler', '0004_job_budget_max_job_budget_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
